CREATE USER 'oke'@'%' IDENTIFIED VIA mysql_native_password USING 'admin';
GRANT ALL PRIVILEGES ON *.* TO 'oke'@'localhost' REQUIRE NONE WITH GRANT OPTION ;MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
REVOKE ALL PRIVILEGES ON *.* FROM 'olive'@'localhost';
